---
author: "Kim Seonghyun"
title: "Quick start"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick start}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE}
library(tropr)
library(ggplot2)
```

### Installation

Either you try stable CRAN version

```{r, eval = F}
install.packages("tropr")
```

Or unstable development version

```{r, eval = F}
devtools::install_github("zedoul/tropr")
```

You'll need to use `library` to load as follows:

```{r, eval = F}
library(tropr)
```

### Get Content

```{r}
library(tropr)

.url <- "http://tvtropes.org/pmwiki/pmwiki.php/Main/SenseiChan"
content <- trope_content(.url)
.df <- as.data.frame(content)
head(.df[, c("category", "link")])
```

The output is `tidy`, so that you can easily turn them into a plot as follows:

```{r}
library(ggplot2)
q <- ggplot(.df, aes(category)) + geom_bar() +
       coord_flip() + ylab("Freq") + xlab("")
plot(q)
```

### Page history analysis

```{r}
library(tropr)
library(ggplot2)
library(dplyr)

.url <- "http://tvtropes.org/pmwiki/pmwiki.php/Characters/LittleWitchAcademia"
hist_content <- trope_history(.url)
.data <- aggr_history_edit_count(hist_content)
.resolution <- "1 week"

# In this case, we are interested in history only after the TV release, and
# before the episode 23
.data <- .data[c(47:169), ]

q <- ggplot(.data, aes(x = date, y = count)) +
    geom_line(size= .8) +
    theme(axis.text.x = element_text(angle = 50, hjust = 1, vjust = 1, size = 8),
          plot.title = element_text(hjust = 0.5)) +
    scale_x_date(date_breaks = .resolution) +
    ggtitle("Edits on Little Witch Academia Main Page in TV Tropes") +
    xlab("") + ylab("#edit")
plot(q)
```

And we can compare the impact of episode 22, with others as follows:

```{r}
library(tropr)
library(ggplot2)
library(magrittr)

impacts <- .data %>% group_by(date = cut(date, "week")) %>% summarise(impact = sum(count))
impacts$date <- paste0("7 days from ", as.character(impacts$date), " (", paste("Episode", rep(1:22)), ")")

q <- ggplot(impacts, aes(x = reorder(date, impact),
                       y = impact,
                       fill = impact)) +
       geom_bar(stat= "identity") +
       theme(axis.text.y = element_text(size = 6)) +
       coord_flip() + ggtitle("Weekly edits on Little Witch Academia Characters Page in TV Tropes") +
       ylab("") + xlab("")
plot(q)
```

```{r}
.data <- aggr_history_editor_count(hist_content)

q <- ggplot(.data, aes(x = reorder(editor, count),
                       y = count,
                       fill = count)) +
       geom_bar(stat= "identity") +
       theme(axis.text.y = element_text(size = 3)) +
       coord_flip() + ggtitle("Editors on Little Witch Academia Characters Page in TV Tropes\n",
                              paste("from", tail(hist_content)[5, "datetime"],
                                    "to", head(hist_content[1, "datetime"]))) +
       ylab("") + xlab("")
plot(q)
```
